
package com.wangqin.globalshop.logistic.app.service.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReceiveEncryptDeclareService", targetNamespace = "http://ws.newyork.zjport.gov.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReceiveEncryptDeclareService {


    /**
     * 
     * @param msgType
     * @param sendCode
     * @param dataDigest
     * @param content
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "receive", targetNamespace = "http://ws.newyork.zjport.gov.cn/", className = "com.wangqin.globalshop.logistic.app.service.Receive")
    @ResponseWrapper(localName = "receiveResponse", targetNamespace = "http://ws.newyork.zjport.gov.cn/", className = "com.wangqin.globalshop.logistic.app.service.ReceiveResponse")
    public String receive(
            @WebParam(name = "content", targetNamespace = "")
                    String content,
            @WebParam(name = "msgType", targetNamespace = "")
                    String msgType,
            @WebParam(name = "dataDigest", targetNamespace = "")
                    String dataDigest,
            @WebParam(name = "sendCode", targetNamespace = "")
                    String sendCode);

}
