
package com.wangqin.globalshop.logistic.app.service.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReceiveEncryptDeclareServiceImplService", targetNamespace = "http://impl.ws.newyork.zjport.gov.cn/", wsdlLocation = "http://122.224.230.4:18003/newyorkWS/ws/ReceiveEncryptDeclare?wsdl")
public class ReceiveEncryptDeclareServiceImplService
    extends Service
{

    private final static URL RECEIVEENCRYPTDECLARESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RECEIVEENCRYPTDECLARESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName RECEIVEENCRYPTDECLARESERVICEIMPLSERVICE_QNAME = new QName("http://impl.ws.newyork.zjport.gov.cn/", "ReceiveEncryptDeclareServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://122.224.230.4:18003/newyorkWS/ws/ReceiveEncryptDeclare?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECEIVEENCRYPTDECLARESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        RECEIVEENCRYPTDECLARESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ReceiveEncryptDeclareServiceImplService() {
        super(__getWsdlLocation(), RECEIVEENCRYPTDECLARESERVICEIMPLSERVICE_QNAME);
    }

    public ReceiveEncryptDeclareServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECEIVEENCRYPTDECLARESERVICEIMPLSERVICE_QNAME, features);
    }

    public ReceiveEncryptDeclareServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, RECEIVEENCRYPTDECLARESERVICEIMPLSERVICE_QNAME);
    }

    public ReceiveEncryptDeclareServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECEIVEENCRYPTDECLARESERVICEIMPLSERVICE_QNAME, features);
    }

    public ReceiveEncryptDeclareServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReceiveEncryptDeclareServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReceiveEncryptDeclareService
     */
    @WebEndpoint(name = "ReceiveEncryptDeclareServiceImplPort")
    public ReceiveEncryptDeclareService getReceiveEncryptDeclareServiceImplPort() {
        return super.getPort(new QName("http://impl.ws.newyork.zjport.gov.cn/", "ReceiveEncryptDeclareServiceImplPort"), ReceiveEncryptDeclareService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReceiveEncryptDeclareService
     */
    @WebEndpoint(name = "ReceiveEncryptDeclareServiceImplPort")
    public ReceiveEncryptDeclareService getReceiveEncryptDeclareServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.ws.newyork.zjport.gov.cn/", "ReceiveEncryptDeclareServiceImplPort"), ReceiveEncryptDeclareService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECEIVEENCRYPTDECLARESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw RECEIVEENCRYPTDECLARESERVICEIMPLSERVICE_EXCEPTION;
        }
        return RECEIVEENCRYPTDECLARESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
